import type { Metadata } from "next";
// import { Danf } from "next/font/google";
import { Poppins } from "@next/font/google";
import "./globals.css";
import SideNavbar from "./components/SideNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--poppins",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`lg:flex bg-[#0d0d0d]" ${poppins.variable}`}>
        <SideNavbar />
        {children}
      </body>
    </html>
  );
}
