import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import ClientProvider from "./providers/ClientProvider";
import RootContent from "./layouts/RootContent";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--poppins",
});

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`lg:flex bg-[#0d0d0d] ${poppins.variable}`}>
        <ClientProvider>
          <RootContent>{children}</RootContent>
        </ClientProvider>
      </body>
    </html>
  );
}
